repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run Django tests
        entry: cmd /c "cd ads_api &&  python manage.py test"
        language: system
        types: [python]

      - id: run-linter
        name: Run flake8
        entry: flake8 ads_api
        language: system
        types: [python]
